workspace:
  base: /go

image-ebayn: &image-alpha
  image: ecr.vip.ebayc3.com/newpro/cd:2.0-alpha

pipeline:

  test:
    image: golang
    commands:
      - go get github.com/cloudflare/cfssl/log
      - go get k8s.io/client-go/...
      - go get -u k8s.io/apimachinery/...
      - go test
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
    when:
      event: [push, pull_request, tag]

  publish:
    <<: *image-alpha
    run: publish
    privileged: true
    environment:
      - GOPATH=/golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push, pull_request, tag]
      branch: [master]

  rollout_dev:
    <<: *image-alpha
    run: rollout
    env: dev
    team: shared
    initiative: restricted
    when:
      event: [push, tag]
      branch: [master]

  rollout_prod:
    <<: *image-alpha
    run: rollout
    env: prod
    team: shared
    initiative: restricted
    when:
      event: [push, tag]
      branch: [master]