workspace:
  base: /go

image-latest: &image-latest
  image: gcr.io/npd-shared/cd:latest

pipeline:

  test:
    image: instrumentisto/glide:0.13.1-go1.9
    commands:
      - glide update
      - go test
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o pod-reaper
    when:
      event: [push, pull_request, tag]

  publish:
    <<: *image-latest
    run: publish
    privileged: true
    environment:
      - GOPATH=/golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tag: latest
    when:
      event: [push, pull_request, tag]
      branch: [master]
