workspace:
  base: /go

image-ebayn: &image-alpha
  image: ecr.vip.ebayc3.com/newpro/cd:TEST-ONLY-force-team-namespace

pipeline:

  test:
    image: golang
    volumes:
      - export GOPATH=/golang
      - /golang:/golang
    commands:
      - go get github.com/cloudflare/cfssl/log
      - go get k8s.io/client-go/...
      - go get -u k8s.io/apimachinery/...
      - go test
      - go build
    when:
      event: [push, pull_request, tag]

  publish:
    <<: *image-alpha
    run: publish
    privileged: true
    environment:
      - GOPATH=/golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /golang:/golang
    when:
      event: [push, pull_request, tag]
      branch: [master,dep]

  rollout_dev:
    <<: *image-alpha
    run: rollout
    env: dev
    team: shared
    initiative: n0
    when:
      event: [push, tag]
      branch: [master, dep]