workspace:
  base: /go

image-latest: &image-latest
  image: gcr.io/npd-shared/cd:latest

pipeline:

  test:
    image: golang
    commands:
      - go get github.com/cloudflare/cfssl/log
      - go get k8s.io/client-go/...
      - go get -u k8s.io/apimachinery/...
      - go test
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
    when:
      event: [push, pull_request, tag]

  publish:
    <<: *image-latest
    run: publish
    privileged: true
    environment:
      - GOPATH=/golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tag: latest
    when:
      event: [push, pull_request, tag]
      branch: [master]
