---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: "1"
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "ghcr.io/kami-no/pod-reaper:latest"
          env:
            - name: CRON_JOB
              value: "{{ .Values.cronJob }}"
            - name: EVICT
              value: "{{ .Values.evict }}"
            - name: MAX_REAP_COUNT_PER_RUN
              value: "{{ .Values.maxReapCountPerRun }}"
            - name: REAP_EVICTED_PODS
              value: "{{ .Values.reapEvictedPods }}"
            - name: REAPER_NAMESPACES
              value: "{{ .Release.Namespace }}"
            - name: REMOTE_EXEC
              value: "true"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 128Mi
